//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public int jobID { get; set; }
        public string coID { get; set; }
        public string jobName { get; set; }
        public string salary { get; set; }
        public Nullable<int> amount { get; set; }
        public string method { get; set; }
        public string level { get; set; }
        public Nullable<bool> sexual { get; set; }
        public string exp { get; set; }
        public string description { get; set; }
        public string requirements { get; set; }
        public string benefits { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
