//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopCV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopCVEntities : DbContext
    {
        public TopCVEntities()
            : base("name=TopCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Carrer> Carrer { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Field> Field { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
    }
}
