//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string Username { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<bool> sexsual { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string avt { get; set; }
        public string CV { get; set; }
        public string coverletter { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
